// ============================================================================
// ℹ️ WORKSHOP SETUP FILE
// ⚠️ DO NOT LOOK HERE FOR BUGS: This file contains hardcoded fallback data for
// local offline/mock execution when Supabase is unreachable.
// ============================================================================
const product = 
  seed => ({
  id: `mock-${seed.slug}`,
  image_url: '',
  created_at: '2026-01-01T00:00:00.000Z',
  ...seed,
});

export const MOCK_PRODUCTS = [
  product({ slug: 'monstera-deliciosa', name: 'Monstera Deliciosa', description: 'The iconic split-leaf plant beloved for its dramatic, fenestrated foliage. A statement piece for any room.', price: 24.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000005', rating: 4.8, review_count: 143, in_stock: true, featured: true, light_level: 'bright-indirect', environment: ['indoor'], lifestyle: ['beginner-friendly'], plant_type: 'foliage', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'snake-plant', name: 'Snake Plant', description: 'Nearly indestructible and a top air purifier. Thrives on neglect and perfect for beginners.', price: 15.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000001', rating: 4.7, review_count: 218, in_stock: true, featured: true, light_level: 'low-light', environment: ['indoor', 'office'], lifestyle: ['beginner-friendly', 'drought-tolerant', 'air-purifying'], plant_type: 'foliage', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'pothos-golden', name: 'Pothos Golden', description: 'Cascading golden-green vines that thrive almost anywhere. A forgiving, fast-growing favorite.', price: 12.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000005', rating: 4.6, review_count: 97, in_stock: true, featured: false, light_level: 'low-light', environment: ['indoor', 'office'], lifestyle: ['beginner-friendly'], plant_type: 'trailing', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'peace-lily', name: 'Peace Lily', description: 'Elegant white blooms and glossy leaves. One of the best air-purifying plants for indoor spaces.', price: 21.99, compare_at_price: 27.99, category_id: 'a1b2c3d4-0001-0000-0000-000000000002', rating: 4.5, review_count: 82, in_stock: true, featured: false, light_level: 'low-light', environment: ['indoor'], lifestyle: ['air-purifying', 'beginner-friendly'], plant_type: 'flowering', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'spider-plant', name: 'Spider Plant', description: 'Cheerful arching leaves and baby offshoots. Excellent at filtering indoor air and easy to propagate.', price: 9.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000006', rating: 4.5, review_count: 164, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor', 'office'], lifestyle: ['pet-friendly', 'air-purifying', 'beginner-friendly'], plant_type: 'trailing', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'fiddle-leaf-fig', name: 'Fiddle Leaf Fig', description: 'Large, violin-shaped leaves make this a dramatic focal point. A designer favorite for modern interiors.', price: 39.99, compare_at_price: 49.99, category_id: 'a1b2c3d4-0001-0000-0000-000000000005', rating: 4.2, review_count: 56, in_stock: true, featured: true, light_level: 'bright-indirect', environment: ['indoor'], lifestyle: ['air-purifying'], plant_type: 'foliage', pot_size: 'large', is_supply: false, supply_type: null }),
  product({ slug: 'boston-fern', name: 'Boston Fern', description: 'Lush, feathery fronds that bring a tropical feel. Loves humidity and bright indirect light.', price: 19.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000005', rating: 4.3, review_count: 74, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor'], lifestyle: ['air-purifying'], plant_type: 'trailing', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'jade-plant', name: 'Jade Plant', description: 'A classic succulent with thick, glossy leaves. Long-lived and said to bring good fortune.', price: 18.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000003', rating: 4.6, review_count: 109, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor', 'patio'], lifestyle: ['beginner-friendly', 'drought-tolerant'], plant_type: 'succulent', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'succulents-trio', name: 'Succulents Trio', description: 'Three hand-selected succulents in complementary colors and textures. Perfect as a gift or desk accent.', price: 14.99, compare_at_price: 19.99, category_id: 'a1b2c3d4-0001-0000-0000-000000000003', rating: 4.4, review_count: 88, in_stock: true, featured: false, light_level: 'full-sun', environment: ['indoor', 'patio'], lifestyle: ['drought-tolerant', 'beginner-friendly'], plant_type: 'succulent', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'calathea-orbifolia', name: 'Calathea Orbifolia', description: 'Stunning silver-striped leaves that move with the light. A true statement plant for plant lovers.', price: 29.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000001', rating: 4.4, review_count: 61, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor'], lifestyle: ['air-purifying'], plant_type: 'foliage', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'african-violet', name: 'African Violet', description: 'Cheerful velvety blooms in purple, pink, or white year-round. Compact and perfect for windowsills.', price: 11.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000004', rating: 4.3, review_count: 47, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor', 'office'], lifestyle: ['beginner-friendly'], plant_type: 'flowering', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'heartleaf-philodendron', name: 'Heartleaf Philodendron', description: 'Heart-shaped glossy leaves on graceful trailing vines. Easy-care and pet-friendly — a true crowd-pleaser.', price: 16.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000006', rating: 4.7, review_count: 132, in_stock: true, featured: true, light_level: 'low-light', environment: ['indoor', 'office'], lifestyle: ['pet-friendly', 'beginner-friendly'], plant_type: 'trailing', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'zz-plant', name: 'ZZ Plant', description: 'Nearly indestructible with waxy, architectural stems. Tolerates low light and infrequent watering.', price: 22.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000001', rating: 4.8, review_count: 175, in_stock: true, featured: false, light_level: 'low-light', environment: ['indoor', 'office'], lifestyle: ['beginner-friendly', 'drought-tolerant'], plant_type: 'foliage', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'aloe-vera', name: 'Aloe Vera', description: 'A medicinal succulent with thick, fleshy leaves. Doubles as a natural remedy for minor burns.', price: 13.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000003', rating: 4.6, review_count: 201, in_stock: true, featured: false, light_level: 'full-sun', environment: ['indoor', 'outdoor', 'patio'], lifestyle: ['beginner-friendly', 'drought-tolerant', 'pet-friendly'], plant_type: 'succulent', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'bird-of-paradise', name: 'Bird of Paradise', description: 'Bold, tropical leaves that create instant drama. Grows tall and thrives in bright light.', price: 44.99, compare_at_price: 59.99, category_id: 'a1b2c3d4-0001-0000-0000-000000000004', rating: 4.5, review_count: 38, in_stock: true, featured: false, light_level: 'full-sun', environment: ['indoor', 'patio'], lifestyle: ['air-purifying'], plant_type: 'foliage', pot_size: 'large', is_supply: false, supply_type: null }),
  product({ slug: 'chinese-money-plant', name: 'Chinese Money Plant', description: 'Perfectly round, pancake-shaped leaves on upright stems. A modern collector\'s favorite that propagates easily.', price: 17.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000006', rating: 4.5, review_count: 93, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor', 'office'], lifestyle: ['pet-friendly', 'beginner-friendly'], plant_type: 'foliage', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'rubber-plant', name: 'Rubber Plant', description: 'Glossy, burgundy leaves with bold architectural presence. Grows into an impressive indoor tree.', price: 26.99, compare_at_price: null, category_id: 'a1b2c3d4-0001-0000-0000-000000000002', rating: 4.4, review_count: 67, in_stock: true, featured: false, light_level: 'bright-indirect', environment: ['indoor'], lifestyle: ['air-purifying'], plant_type: 'foliage', pot_size: 'medium', is_supply: false, supply_type: null }),
  product({ slug: 'string-of-pearls', name: 'String of Pearls', description: 'Tiny round beads cascade like a waterfall from hanging pots. A show-stopping, unusual succulent.', price: 15.99, compare_at_price: 20.99, category_id: 'a1b2c3d4-0001-0000-0000-000000000003', rating: 4.2, review_count: 42, in_stock: false, featured: false, light_level: 'full-sun', environment: ['indoor', 'patio'], lifestyle: ['drought-tolerant'], plant_type: 'trailing', pot_size: 'small', is_supply: false, supply_type: null }),
  product({ slug: 'pruning-shears', name: 'Pruning Shears', description: 'Sharp, ergonomic bypass pruners for clean cuts on stems and branches. Stainless steel blades with comfortable grips.', price: 18.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'tool' }),
  product({ slug: 'copper-watering-can', name: 'Copper Watering Can', description: 'Elegant 1.2L copper-finish can with a long spout for precise watering. Balances beautifully and resists rust.', price: 28.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'tool' }),
  product({ slug: 'plant-mister-bottle', name: 'Plant Mister Bottle', description: 'Fine-mist sprayer in frosted glass. Perfect for humidity-loving tropicals and foliar feeding.', price: 9.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'tool' }),
  product({ slug: 'terracotta-pots-set', name: 'Terracotta Pots Set (3-Pack)', description: 'Classic unglazed terracotta in three sizes (4\", 6\", 8\"). Breathable walls encourage healthy roots.', price: 22.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'pot' }),
  product({ slug: 'speckled-ceramic-pot', name: 'Speckled Ceramic Pot', description: 'Hand-dipped sage green glaze with natural speckle texture. 5\" diameter with drainage hole and saucer.', price: 26.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'pot' }),
  product({ slug: 'woven-hanging-planter', name: 'Woven Hanging Planter', description: 'Natural jute macramé hanger. Adds texture and height to any plant display.', price: 19.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'pot' }),
  product({ slug: 'premium-potting-mix', name: 'Premium Potting Mix (8qt)', description: 'Rich, well-draining blend with perlite, coco coir, and compost. Suitable for most tropical houseplants.', price: 14.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'soil' }),
  product({ slug: 'succulent-cactus-mix', name: 'Succulent & Cactus Mix (4qt)', description: 'Fast-draining gritty mix with coarse sand and pumice. Prevents root rot in drought-tolerant plants.', price: 11.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'soil' }),
  product({ slug: 'orchid-bark-mix', name: 'Orchid Bark Mix (4qt)', description: 'Chunky fir bark blend that promotes excellent airflow around orchid roots. Suitable for epiphytes.', price: 13.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'soil' }),
  product({ slug: 'slow-release-fertilizer', name: 'Slow-Release Fertilizer (1lb)', description: 'Balanced NPK granules that feed for up to 6 months. Gentle enough for all houseplants without risk of burn.', price: 16.99, compare_at_price: null, category_id: '', rating: 0, review_count: 0, in_stock: true, featured: false, light_level: null, environment: null, lifestyle: null, plant_type: null, pot_size: null, is_supply: true, supply_type: 'soil' }),
];

export const MOCK_CATEGORIES = [
  { id: 'a1b2c3d4-0001-0000-0000-000000000001', name: 'Low-Light Champions', slug: 'low-light', description: 'Thrive in shade and low-light conditions', image_url: 'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
  { id: 'a1b2c3d4-0001-0000-0000-000000000002', name: 'Air-Purifying', slug: 'air-purifying', description: 'Clean your air naturally', image_url: 'https://images.pexels.com/photos/793012/pexels-photo-793012.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
  { id: 'a1b2c3d4-0001-0000-0000-000000000003', name: 'Succulents & Cacti', slug: 'succulents', description: 'Easy, drought-tolerant beauties', image_url: 'https://images.pexels.com/photos/1470171/pexels-photo-1470171.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
  { id: 'a1b2c3d4-0001-0000-0000-000000000004', name: 'Flowering Plants', slug: 'flowering', description: 'Add color to any room', image_url: 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
  { id: 'a1b2c3d4-0001-0000-0000-000000000005', name: 'Trailing & Hanging', slug: 'trailing', description: 'Perfect for shelves and high spots', image_url: 'https://images.pexels.com/photos/1446093/pexels-photo-1446093.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
  { id: 'a1b2c3d4-0001-0000-0000-000000000006', name: 'Pet-Friendly', slug: 'pet-friendly', description: 'Safe for cats and dogs', image_url: 'https://images.pexels.com/photos/4751978/pexels-photo-4751978.jpeg?auto=compress&cs=tinysrgb&w=800', created_at: '2026-01-01T00:00:00.000Z' },
];

export const MOCK_COUPONS= [
  { id: 'mock-ghc2026', code: 'GHC2026', description: 'Grace Hopper Celebration — 20% off your order', discount_type: 'percent', discount_value: 20, active: true, max_uses: null, times_used: 0, expires_at: null },
  { id: 'mock-plantlove', code: 'PLANTLOVE', description: 'Plant lover special — $15 off', discount_type: 'fixed', discount_value: 15, active: true, max_uses: null, times_used: 0, expires_at: null },
  { id: 'mock-welcome10', code: 'WELCOME10', description: 'Welcome discount — 10% off', discount_type: 'percent', discount_value: 10, active: true, max_uses: 100, times_used: 0, expires_at: null },
  { id: 'mock-megadeal', code: 'MEGADEAL', description: 'Mega deal — $25 off your order', discount_type: 'fixed', discount_value: 25, active: true, max_uses: 50, times_used: 0, expires_at: null },
];